data:
  image: busybox:1
  volumes:
    - /data/knowledge:/root/.knowledge
knowledge:
  image: koda/docker-knowledge
  ports:
    - "8080:8080"
  volumes_from:
    - data
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/html:/usr/share/nginx/html
  links:
    - knowledge:knowledge
