FROM m411momo/tomcat8:1.0
MAINTAINER Masahiro Saito

ADD https://github.com/support-project/knowledge/releases/download/v1.4.1/knowledge.war /apache-tomcat-8.0.36/webapps/knowledge.war

VOLUME [ "/root/.knowledge" ]

EXPOSE 8080